# Generated by Django 4.1.7 on 2023-04-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'worst'), (2, 'bad'), (3, 'good')]),
        ),
    ]
